        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 27 16:27:22 2020
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE COMPUTE_AVE_OD_AQ_MODIFIED__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_AVE_OD_AQ_MODIFIED(ATMNAM_WC,NWATERS,    &
     &NSTEP,INI,SKIP,ATM_W1,ATM_W2,ATM_W3,ATM_W4,ATM_W5,ATM_W6,ATM_W7,  &
     &ATM_W8,ATM_W9,ATM_W10,ATM_W11,ATM_W12,ATM_W13,ATM_W14,ATM_W15,    &
     &ATM_W16,ATM_W17,ATM_W18,MUX,MUY,MUZ,TCF_AUTO_ALL,TCF_CROSS_ALL)
              INTEGER(KIND=4), INTENT(IN) :: NSTEP
              INTEGER(KIND=4), INTENT(IN) :: NWATERS
              CHARACTER(LEN=8), INTENT(IN) :: ATMNAM_WC(NSTEP,NWATERS)
              INTEGER(KIND=4), INTENT(IN) :: INI
              INTEGER(KIND=4), INTENT(IN) :: SKIP
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W1
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W2
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W3
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W4
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W5
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W6
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W7
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W8
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W9
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W10
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W11
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W12
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W13
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W14
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W15
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W16
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W17
              CHARACTER(LEN=8), INTENT(IN) :: ATM_W18
              REAL(KIND=8), INTENT(IN) :: MUX(NSTEP,NWATERS)
              REAL(KIND=8), INTENT(IN) :: MUY(NSTEP,NWATERS)
              REAL(KIND=8), INTENT(IN) :: MUZ(NSTEP,NWATERS)
              REAL(KIND=8), INTENT(OUT) :: TCF_AUTO_ALL(18,NSTEP)
              REAL(KIND=8), INTENT(OUT) :: TCF_CROSS_ALL(18,NSTEP)
            END SUBROUTINE COMPUTE_AVE_OD_AQ_MODIFIED
          END INTERFACE 
        END MODULE COMPUTE_AVE_OD_AQ_MODIFIED__genmod
